### ISSUE TITLE
prediction error: problem joining the base and head models

### ISSUE THREAD

**Issue by koustav123** [subpic/ava-mlsp#3]
Hi,
I get an error while executing the following line in the file predict_mlsp_wide.ipynb
```
helper.model = Model(inputs  = model_base.input,
                     outputs = model(model_base.output))
```

The error is

```
Traceback (most recent call last):
  File "predict_mlsp_wide.py", line 73, in <module>
    outputs = model(model_base.output))
  File "/root/anaconda2/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/engine/network.py", line 721, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/root/anaconda2/lib/python2.7/site-packages/keras/layers/normalization.py", line 197, in call
    self.momentum),
  File "/root/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1014, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 653, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable 3x3_1x1_bn/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/root/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1014, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/layers/normalization.py", line 197, in call
    self.momentum),
  File "/root/anaconda2/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)


```

I am running the script inside a docker container with the specified tensorflow-gpu and keras-gpu versions. The feature extraction and training worked fine. 

Any pointers? Thanks a million

**Comment by subpic** [comment]
Off the top of my head: are you loading multiple base models in the same session? That might cause a name clash in the added layers. In that case, try using different name prefixes for the layers.
Otherwise, try the newer [ku library](https://github.com/subpic/ku), a replacement for kutils. It might help.

Best,
Vlad

**Comment by koustav123** [comment]
It seems the problem was TF version. I was able to reproduce the results with TF 1.15. A pip freeze in the colab environment shows 1.15. But in the readme file its 1.14.

**Comment by subpic** [comment]
Good to know it works, thanks for pointing it out.
